"""Bazel test that exercises the sphinx-needs-based documentation
traceability mechanism end-to-end (the approach eclipse-score's
docs-as-code tooling is built on): it runs `sphinx-build -W` over
docs_needs/ and fails the build if any `:links:` reference is dangling.

Unlike strictdoc_traceability_test.py, this only checks doc-to-doc links;
sphinx-needs has no built-in equivalent of StrictDoc's source-code
`@relation(...)` markers, so it cannot detect a stale `src/calculator.py`
path mentioned in docs_needs/implementation.rst. See README.md.
"""

import subprocess
import tempfile
import unittest
from pathlib import Path

from python.runfiles import runfiles


class SphinxNeedsTraceabilityTest(unittest.TestCase):
    def test_sphinx_build_succeeds_with_warnings_as_errors(self):
        r = runfiles.Create()
        sphinx_build_bin = r.Rlocation("_main/sphinx-build")
        conf_path = r.Rlocation("_main/docs_needs/conf.py")

        self.assertTrue(
            sphinx_build_bin, "could not resolve the //:sphinx-build runfile"
        )
        self.assertTrue(
            conf_path, "could not resolve the docs_needs/conf.py runfile"
        )

        source_dir = str(Path(conf_path).parent)

        with tempfile.TemporaryDirectory() as out_dir:
            result = subprocess.run(
                [
                    sphinx_build_bin,
                    "-W",  # treat warnings (incl. dangling :links:) as errors
                    "-b",
                    "html",
                    source_dir,
                    out_dir,
                ],
                capture_output=True,
                text=True,
            )

            if result.returncode != 0:
                self.fail(
                    "sphinx-build failed - documentation traceability is "
                    "broken (dangling `:links:` reference):\n"
                    + result.stdout
                    + result.stderr
                )

            html_index = Path(out_dir) / "index.html"
            self.assertTrue(
                html_index.exists(),
                f"expected {html_index} to be generated by sphinx-build",
            )


if __name__ == "__main__":
    unittest.main()
