"""Bazel test that exercises the StrictDoc-based documentation traceability
mechanism end-to-end: it runs `strictdoc export` over modules/ (each
module's own docs/, src/, tests/) and fails the build if any requirement
<-> architecture <-> source relation is broken (missing UID, missing
file, etc.), the same way eclipse-score's docs-as-code tooling gates
traceability in CI.
"""

import subprocess
import sys
import tempfile
import unittest
from pathlib import Path

from python.runfiles import runfiles


class TraceabilityTest(unittest.TestCase):
    def test_strictdoc_export_succeeds(self):
        r = runfiles.Create()
        strictdoc_bin = r.Rlocation("_main/strictdoc")
        config_path = r.Rlocation("_main/strictdoc_config.py")

        self.assertTrue(
            strictdoc_bin, "could not resolve the //:strictdoc runfile"
        )
        self.assertTrue(
            config_path, "could not resolve the strictdoc_config.py runfile"
        )

        project_root = str(Path(config_path).parent)

        with tempfile.TemporaryDirectory() as out_dir:
            result = subprocess.run(
                [
                    strictdoc_bin,
                    "export",
                    project_root,
                    "--output-dir",
                    out_dir,
                    "--no-parallelization",
                ],
                capture_output=True,
                text=True,
            )

            if result.returncode != 0:
                self.fail(
                    "strictdoc export failed - documentation traceability "
                    "is broken (dangling requirement/source relation):\n"
                    + result.stdout
                    + result.stderr
                )

            html_index = Path(out_dir) / "html" / "index.html"
            self.assertTrue(
                html_index.exists(),
                f"expected {html_index} to be generated by strictdoc export",
            )


if __name__ == "__main__":
    unittest.main()
