/*
 * File: speed_controller.c
 *
 * Code generated for Simulink model 'speed_controller'.
 * See speed_controller.h for the generation-fidelity disclaimer and
 * models/speed_controller.md for the block diagram.
 *
 * DO NOT EDIT THIS FILE BY HAND.
 */
#include "src/speed_controller/speed_controller.h"

/* Block signals and states (default storage) */
static DW_speed_controller_T speed_controller_DW;

/* External inputs */
ExtU_speed_controller_T speed_controller_U;

/* External outputs */
ExtY_speed_controller_T speed_controller_Y;

/* Parameters (tunable, default storage) */
P_speed_controller_T speed_controller_P = {
    2.0,   /* Kp_Gain */
    0.5,   /* Ki_Gain */
    0.1,   /* SampleTime */
    100.0, /* Saturation_UpperSat */
    -100.0 /* Saturation_LowerSat */
};

/* Model step function */
void speed_controller_step(void) {
  real_T rtb_Sum;

  /* Sum: '<Root>/Sum' incorporates:
   *  Gain: '<Root>/Kp'
   *  Integrator: '<Root>/Integrator'
   */
  rtb_Sum = (speed_controller_U.Error * speed_controller_P.Kp_Gain) +
            speed_controller_DW.Integrator_DSTATE;

  /* Saturate: '<Root>/Saturation' */
  if (rtb_Sum > speed_controller_P.Saturation_UpperSat) {
    speed_controller_Y.Command = speed_controller_P.Saturation_UpperSat;
  } else if (rtb_Sum < speed_controller_P.Saturation_LowerSat) {
    speed_controller_Y.Command = speed_controller_P.Saturation_LowerSat;
  } else {
    speed_controller_Y.Command = rtb_Sum;
  }

  /* Update for Integrator: '<Root>/Integrator' incorporates:
   *  Gain: '<Root>/Ki'
   */
  speed_controller_DW.Integrator_DSTATE +=
      speed_controller_P.Ki_Gain * speed_controller_U.Error *
      speed_controller_P.SampleTime;
}

/* Model initialize function */
void speed_controller_initialize(void) {
  speed_controller_DW.Integrator_DSTATE = 0.0;
  speed_controller_U.Error = 0.0;
  speed_controller_Y.Command = 0.0;
}

/* Model terminate function */
void speed_controller_terminate(void) {
  /* (no terminate code required) */
}
