/*
 * File: speed_controller.h
 *
 * Code generated for Simulink model 'speed_controller'.
 *
 * NOTE: hand-authored to mirror the structure Simulink Embedded Coder
 * emits for a discrete PI-with-saturation model (banner comments,
 * ExtU_/ExtY_/DW_/P_ structs, <model>_initialize/_step/_terminate entry
 * points) -- no MATLAB/Simulink toolchain was available to generate it
 * for real. See ../models/speed_controller.md for the block diagram this
 * corresponds to, and the repository's top-level README.md for how this
 * module's traceability differs from the other six (hand-written)
 * modules.
 *
 * Model version                  : 1.4
 * Simulink Coder version         : 24.2 (R2024b) (illustrative)
 *
 * DO NOT EDIT THIS FILE BY HAND. Regenerate it from the Simulink model
 * instead -- manual changes are lost on the next code generation.
 */
#ifndef SPEED_CONTROLLER_H_
#define SPEED_CONTROLLER_H_

#include "modules/speed_controller/src/rtwtypes.h"

#ifdef __cplusplus
extern "C" {
#endif

/* Block signals and states (default storage) for model 'speed_controller' */
typedef struct {
  real_T Integrator_DSTATE; /* '<Root>/Integrator' */
} DW_speed_controller_T;

/* External inputs for model 'speed_controller' */
typedef struct {
  real_T Error; /* '<Root>/Error' */
} ExtU_speed_controller_T;

/* External outputs for model 'speed_controller' */
typedef struct {
  real_T Command; /* '<Root>/Command' */
} ExtY_speed_controller_T;

/* Parameters (default storage) for model 'speed_controller' */
typedef struct {
  real_T Kp_Gain;             /* Mask Parameter: Kp */
  real_T Ki_Gain;             /* Mask Parameter: Ki */
  real_T SampleTime;          /* Mask Parameter: SampleTime */
  real_T Saturation_UpperSat; /* Mask Parameter: UpperLimit */
  real_T Saturation_LowerSat; /* Mask Parameter: LowerLimit */
} P_speed_controller_T;

extern ExtU_speed_controller_T speed_controller_U;
extern ExtY_speed_controller_T speed_controller_Y;
extern P_speed_controller_T speed_controller_P;

extern void speed_controller_initialize(void);
extern void speed_controller_step(void);
extern void speed_controller_terminate(void);

#ifdef __cplusplus
}
#endif

#endif /* SPEED_CONTROLLER_H_ */
