// @relation(ARCH-7, scope=file, role=Test)
//
// Unlike the other module tests, ARCH-7 links to ../src/* via a doc-side
// `TYPE: File` relation (see ../docs/architecture.sdoc) rather than an
// in-file marker, because that code is Simulink-generated and must not
// be hand-edited. This test file itself is hand-written, so it carries
// the usual source marker.
extern "C" {
#include "modules/speed_controller/src/speed_controller.h"
}

#include <gtest/gtest.h>

// speed_controller_U/_Y/_DW are global state (as generated by Embedded
// Coder), so each test re-initializes the model to stay independent of
// test execution order.
class SpeedControllerTest : public ::testing::Test {
 protected:
  void SetUp() override { speed_controller_initialize(); }
};

TEST_F(SpeedControllerTest, ProportionalTermDominatesOnFirstStep) {
  speed_controller_U.Error = 10.0;
  speed_controller_step();

  // Kp * error, integrator still 0.
  EXPECT_DOUBLE_EQ(speed_controller_Y.Command, 20.0);
}

TEST_F(SpeedControllerTest, IntegratorAccumulatesAcrossSteps) {
  speed_controller_U.Error = 10.0;
  speed_controller_step();
  speed_controller_step();

  // Second step includes the accumulated integrator term:
  // Ki * error * SampleTime = 0.5 * 10 * 0.1 = 0.5.
  EXPECT_DOUBLE_EQ(speed_controller_Y.Command, 20.5);
}

TEST_F(SpeedControllerTest, LargeErrorSaturatesAtTheUpperLimit) {
  speed_controller_U.Error = 1000.0;
  speed_controller_step();

  EXPECT_DOUBLE_EQ(speed_controller_Y.Command, 100.0);
}
